### ISSUE TITLE
Cannot find `/dev/cu.usbmodem1411` port on macOS Sierra

### ISSUE THREAD

**Issue by fredwulei** [twosigma/blinky#12]
I cannot find `/dev/cu.usbmodem1411` port on the latest macOS 10.12 Sierra, there is no related item under USB bus in the System Report either.

**Comment by fredwulei** [comment]
NVM, I forgot to turn to "ON" when plugging to the computer, feel so sad about myself 😭

**Comment by rpf5573** [comment]
> NVM, I forgot to turn to "ON" when plugging to the computer, feel so sad about myself 😭

What did you turn to ON ???
I'm facing same error.

**Comment by fredwulei** [comment]
The physical switch on the blinky hardware, you need to turn on its power first, this is not like the usual device that will be automatically turned on when connect to USB, lol
